# Generated by Django 4.2.7 on 2023-11-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movietheatre',
            options={'verbose_name': 'Кинотеатр', 'verbose_name_plural': 'Кинотеатры'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', 'comedy'), ('animation', 'animation'), ('horror', 'horror'), ('drama', 'drama'), ('sci-fi', 'sci-fi')], max_length=10),
        ),
    ]
